### ISSUE TITLE
llama3:8b -> llama3.1:8b

### ISSUE THREAD

**Issue by t-honma-mico** [gpgkd906/tdd_agents#1]
In the curl command in README for testing ollama, the request has `"model": "llama3:8b"`. I think it should be  `"model": "llama3.1:8b"`.<br>
`.env.ollama` should be changed as well (`MODEL="llama3:8b"` -> `MODEL="llama3.1:8b"`).

**Comment by t-honma-mico** [comment]
.env.ollama should be changed as well (`MODEL="llama3:8b"` -> `MODEL="llama3.1:8b"`).

**Comment by gpgkd906** [comment]
Thank you! @t-honma-mico 
I've modified the readme so that all the instructions are standardized to llama3:8b.
Since I did the benchmark, there is no difference in code generation between the two models.
(actually the openai gpt4 is better.)
So I went with the one with less modifications.
But you can modify the .env yourself to match llama3.1:8b.
Thanks again!

**Comment by t-honma-mico** [comment]
Thank you. It works now.
